### ISSUE TITLE
Fake-transparency

### ISSUE THREAD

**Issue by EvilPudding** [chjj/compton#453]
Is there anyway to have a fake-transparency setting, so the user may set a specific image for all windows with transparency?

I'm trying to do it myself, but don't know my way around the codebase that well...

Thanks!

**Comment by 0x041E** [comment]
I don't really understand why would you want to fake transparency using compositor which does real transparency. Fake transparency is not what compositor is supposed to do it's up to the given program to implement fake transparency ... if it's for terminal windows then terminal emulators usually provide some fake transparency settings at least URxvt and Terminology support that, not sure about others.

**Comment by EvilPudding** [comment]
I am using urxvt fake transparency, but I want to have it on all programs.

I have a script that blurs my chosen wallpaper with a quality and amount that would not be possible in real time with compton, I then am using it as the fake background of urxvt, but I want unfocused windows with lower opacity to have it as well.

Why would this not be a useful tool? It seems pretty easy to implement and my case may be just one of the possibilities it opens, who knows what else the community might create with it?

**Comment by ChrisOboe** [comment]
I also think that fake transparency would be nice. When using i3 in tabbed mode with real transparency you will see the content of another tab instead of the background. With fake transparency you would see background.

**Comment by 0x041E** [comment]
@ChrisOboe use
```
opacity-rule = [
  "0:_NET_WM_STATE@[0]:32a = '_NET_WM_STATE_HIDDEN'",
  "0:_NET_WM_STATE@[1]:32a = '_NET_WM_STATE_HIDDEN'",
  "0:_NET_WM_STATE@[2]:32a = '_NET_WM_STATE_HIDDEN'",
  "0:_NET_WM_STATE@[3]:32a = '_NET_WM_STATE_HIDDEN'",
  "0:_NET_WM_STATE@[4]:32a = '_NET_WM_STATE_HIDDEN'",

  "90:_NET_WM_STATE@[0]:32a = '_NET_WM_STATE_STICKY'",
  "90:_NET_WM_STATE@[1]:32a = '_NET_WM_STATE_STICKY'",
  "90:_NET_WM_STATE@[2]:32a = '_NET_WM_STATE_STICKY'",
  "90:_NET_WM_STATE@[3]:32a = '_NET_WM_STATE_STICKY'",
  "90:_NET_WM_STATE@[4]:32a = '_NET_WM_STATE_STICKY'"
];
```
for i3 it should fix that i've used it when i used to use i3

**Comment by ChrisOboe** [comment]
@0x041E thank you, with these rules it works fine.

**Comment by EvilPudding** [comment]
Doesn't solve my problem though, if it's not implemented I will keep a fork of it just for me, if no one else thinks it's worth it...

**Comment by EvilPudding** [comment]
I need to know if this is going to be implemented, I understand if you don't want it, but I need to know if I can expect it of if I should start working on it myself.

**Comment by EvilPudding** [comment]
If having the ability to pick a fake background image is outside of the scope of this compositor, how about having the ability to cache the blurred background, and use that for all transparency?

It would accomplish what I what without having to implement picture loading.

**Comment by klopsi** [comment]
I think that the way to get what you call 'fake transparency to a background image' is to do keycolor transparency to root window (aka desktop background) -- instead of to underlying windows.

I am also interested in transparency to <b>root window</b> using black as the keycolor (instead of transparency to underlying windows).  Please see example at:

<img>https://abload.de/img/comptonexample5kugv.png</img>

Notice that the graphics, window decorations and text are non-transparent with keycolor transparency on the right.  Readability is improved by this, and also especially by not seeing the underlying windows.  

I found keycolor transparency implemented in compton via glsl shader.  How to make this transparent to root and not to underlying window?  

Cheers!

**Comment by EvilPudding** [comment]
I've just dug into the code to do what I wanted and made a patchwork fork.
